name: "Web MVC - CI"

on:
  push:
    paths: 
    - src/Web/WebMVC/**
    - .github/workflows/webmvc.yml
    - deploy/k8s/helm/webmvc/**

jobs:
  build:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        cfg:
        - {os: ububtu-18.04, arch: linux}
        - {os: windows-2019, arch: windows}

    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file Dockerfile --tag eshop/webspa:${{ matrix.cfg.arch }}-${{ github.sha }}
      working-directory: src/Web/WebMVC/
      name: "Build docker image"
