name: "Web SPA - CI"

on:
  push:
    paths: 
    - src/Web/webspa/**
    - .github/workflows/webspa.yml
    - deploy/k8s/helm/webspa/**

jobs:
  build:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        cfg:
        - {os: ubuntu-18.04, arch: linux}
        - {os: windows-2019, arch: windows}

    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file Web/WebSPA/Dockerfile --tag eshop/webspa:${{ matrix.cfg.arch }}-${{ github.sha }}
      working-directory: src
      name: "Build docker image"
