name: "Web Status - CI"

on:
  push:
    paths: 
    - src/Web/WebStatus/**
    - .github/workflows/webstatus.yml
    - deploy/k8s/helm/webstatus/**

jobs:
  build:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        cfg:
        - {os: ubuntu-18.04, arch: linux}
        - {os: windows-2019, arch: windows}

    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file Web/WebStatus/Dockerfile --tag eshop/webstatus:${{ matrix.cfg.arch }}-${{ github.sha }}
      working-directory: src
      name: "Build docker image"
